fix Closure Compiler fetching, pin to a specific release

diff --git a/bin/deps b/bin/deps
--- a/bin/deps
+++ b/bin/deps
@@ -14,12 +14,12 @@ npm install grunt
 
 echo "Installing JVM dependencies"
 
+CLOSURE_RELEASE="20210302"
 mkdir -p deps/closure-compiler
 cd deps/closure-compiler
-curl -O -s http://dl.google.com/closure-compiler/compiler-latest.zip
-unzip -qu compiler-latest.zip
+echo "Fetching Google Closure compiler..."
+curl --retry 3 -O -s https://repo1.maven.org/maven2/com/google/javascript/closure-compiler/v$CLOSURE_RELEASE/closure-compiler-v$CLOSURE_RELEASE.jar || { echo "Download failed."; exit 1; }
 mv closure-compiler-**.jar compiler.jar
-rm compiler-latest.zip
 cd ../..
 
 git clone https://github.com/google/closure-library.git deps/closure-library
